on: workflow_dispatch
# on:
#   schedule:
#     - cron:  '* 6 * * 0'
name: Weekly rebuild
jobs:
  generate:
    name: generate annotated epub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: install-deps
        run: |
          sudo apt-get update
          sudo apt-get remove python
          sudo apt-get install python3 tidy calibre python3-pip
          sudo -H pip3 install setuptools
          sudo -H pip3 install ebookmaker pytidylib
      - name: get ideacrawler
        run: |
          go get github.com/shsms/ideacrawler
          # git clone https://github.com/shsms/ideacrawler
          # cd ideacrawler && go build
      - name: get mime
        run: |
          curl -OL https://github.com/shsms/mime/releases/latest/download/mime-linux-amd64.tar.gz
          tar -xvf mime-linux-amd64.tar.gz
          chmod +x mime
      - name: download annotations
        run: |
          ~/go/bin/ideacrawler &>/dev/null &
          sleep 1
          make -C scripts download
          killall ideacrawler
        timeout-minutes: 10
      - name: add annotations
        run: |
          MIME=../mime make -C scripts addanno
      - name: generate epub
        run: |
          export PATH=$PATH:${PWD}
          make -C scripts epub
      - name: env vars
        run: echo "MY_DATE=$(date +%Y.%m.%d)" >> $GITHUB_ENV
      - name: Create Release
        id: createrelease
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.MY_DATE }}-alpha
          release_name: ${{ env.MY_DATE }}-alpha
          draft: true
          prerelease: true
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ steps.createrelease.outputs.id }}
          args: 'ulysses-annotated*.epub'

        
